image: alpine/edge
packages:
  - hugo
  - rsync
sources:
  - https://git.sr.ht/~iwanidev/iwani.dev
secrets:
  - 84e04ddc-bb5a-4c5c-b849-e956a1ebf67e
tasks:
  - setup: |
      hugo env
  - build: |
      cd iwani.dev
      hugo
  - deploy: |
      cd iwani.dev
      sshopts="ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no"
      rsync -r public/* --rsh="$sshopts" cicero.iwani.dev:/var/www/iwani/
